syntax = "proto3";

package delivery;

service DeliveryService {
  rpc AssignDelivery (AssignRequest) returns (DeliveryResponse);
  rpc GetDelivery (GetRequest) returns (DeliveryResponse);
  rpc GetDeliveries (Empty) returns (DeliveryListResponse);
  rpc UpdateDeliveryStatus (UpdateStatusRequest) returns (DeliveryResponse);
  rpc GetOrders (Empty) returns (OrderListResponse); 
}

message AssignRequest {
  int32 order_id = 1;
  string address = 2;
}

message GetRequest {
  string id = 1;
}

message Empty {}

message DeliveryResponse {
  string id = 1;
  int32 order_id = 2;
  string address = 3;
  string status = 4;
}

message DeliveryListResponse {
  repeated DeliveryResponse deliveries = 1;
}

message UpdateStatusRequest {
  string id = 1;
  string status = 2;
}

// Messages ajoutés pour structurer la liste des commandes
message OrderResponse {
  int32 id = 1;
}

message OrderListResponse {
  repeated OrderResponse orders = 1;
}